### ISSUE TITLE
Support MultiTenancy

### ISSUE THREAD

**Issue by ajres** [couchbase/sync_gateway#2124]
### Potential use cases
1. Multiple Sync Gateway databases targeting a single bucket, sharing a single set of users
   - e.g. single organization building multiple apps for a common user base
   - want to define separate Sync Functions for each tenant
2. Multiple Sync Gateway databases targeting a single bucket, each with independent/isolated set of users
   - e.g. hosting company wants to run SG as a service, e.g. cloning an app for multiple tenants
   - want to define separate Sync Functions for each tenant (probably?)
### Requirements
1. Namespaced document IDs.  In either of the cases above, it's expected that multiple tenants would end up trying to write the same doc ID.  Even if in case 1 the single org attempts to isolate doc id namespaces, it would still probably make more sense to SG to provide that guarantee instead of relying on the consumer.  Should also include local docs (possibly not strictly necessary for replication checkpoints, given uniqueness of database uuid, but would cover non-checkpoint local docs being pushed, etc)
2. Namespaced channel IDs.
3. Namespaced role IDs.
4. (Optional) Namespaced users (for use case 2)
5. To scale beyond a small number of tenants/databases, would want Sync Gateway to only work a single TAP/DCP feed per bucket (not per db/tenant).  Without that, adding more than a handful of tenants would have the potential to overload the Couchbase Server cluster.
6. User-created views should be namespaced, and the SG wrapper for the map function should include document filtering by namespace.
7.  Sync Gateway's internal view results should be filtered by namespace.  Could be done as post-processing, but ideally should be done as view-level filtering (i.e. emit tenant as one of the keys)
8. Namespaced _sync:seq?

This might be as low-level as 100% key-based namespacing, so that every document operation by sync gateway does key prefixing.  This could be implemented as a namespaced bucket implementation for KV operations, but would need additional work to handle non-KV functionality (DCP feed, views)
### Questions/considerations
1. In the case where a customer wants to define a large number of tenants, does it make more sense from a performance perspective for those tenants to be backed by multiple Couchbase Server clusters.  i.e. are we defining multitenancy in a way that doesn't end up with the ideal topology for the load.
2. How much of this could addressed via an external proxy doing request rewrites against a single Sync Gateway database?  Wouldn't handle the multiple sync function requirement, but could provide tenant data isolation.
3. May need bucket-level flag to handle the case where one SG config targets a bucket in multi-tenant mode, and another SG config targets the same bucket in normal mode
4. Aside from the implementation work, would require a significant amount of testing enhancements

Support multiple Sync Gateway databases backed by a single bucket.
This could be used to support collaborative development.

The proposed approach is to use a namespace prefix to stripe the data in the DB.
- [ ] Update DB Config to support a namespace per database - #2125
- [ ] Generate a unique _sync:seq document for each namespace - #2126
- [ ] Support channel grants for a user across multiple namespaces - #2127
- [ ] Write namespace into document metadata on all write operations - #2128
- [ ] Update sync function to prefix namespace - #2129
- [ ] Update all rest API calls to use the namespace prefix in the document metadata - #2130
- [ ] Update \* and ! channel handling to apply namespace filtering - #2131
- [ ] Only cache channels with prefixes matching the current DB namespace - #2132
- [ ] Prefix namespace to channels/roles added via the admin REST API - #2134
- [ ] Update _all_docs to filter documents based on namespace - #2135
- [ ] Update _resync to filter documents based on namespace - #2136
- [ ] Update the db/_flush operation to manually remove documents from CBS with the namespace prefix - #2137
- [ ] Support multi tenancy in SG Admin UI - #2138

**Comment by tleyden** [comment]
@ajres I think something went wrong when you tried to file this ticket

**Comment by ajres** [comment]
If we store the namespace in document metadata, I don't think the namespace ever needs to be exposed on the REST API.

**Comment by adamcfraser** [comment]
Closing - any future multitenancy approaches will need to consider collection support.
