### ISSUE TITLE
Move to GSI for internal query operations

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#2664]
- [x] Bucket API enhancements (https://github.com/couchbase/sync_gateway/issues/3350)
 - [ ] Index and Query Definitions (https://github.com/couchbase/sync_gateway/issues/3351)
 - [ ] Config changes (https://github.com/couchbase/sync_gateway/issues/3352)
 - [ ] Install and upgrade (https://github.com/couchbase/sync_gateway/issues/3353)
