### ISSUE TITLE
Log Redaction

### ISSUE THREAD

**Issue by djpongh** [couchbase/sync_gateway#3259]
Tracking issue for Log Redaction epic

**Comment by bbrks** [comment]
Sub-tasks for completion of Log Redaction epic:
- [x] #3295 Infrastructure to support redacted logging
- [x] #3296 Update sgcollect_info to support log redaction
- [x] #3297 Log redaction: 'auth' package
- [x] #3310 Log redaction: 'base' package
- [x] #3311 Log redaction: 'channels' package
- [x] #3312 Log redaction: 'db' package
- [x] #3313 Log redaction: 'rest' package
- [x] #3355 Log redaction: sgcollect_info should redact data in running_server_config.log
