### ISSUE TITLE
GSI integration test failures due to index rollback errors after Bucket flushes

### ISSUE THREAD

**Issue by adamcfraser** [couchbase/sync_gateway#3422]
https://github.com/couchbase/sync_gateway/pull/3417#issuecomment-379141949

Able to repro fairly reliably running:
SG_TEST_BACKING_STORE=Couchbase ./test.sh -v -run=TestLowSequence

## Todo

- [ ] Look into dropping the index before the bucket flush (might need to be spun off into another issue)
- [ ] Verify that dropping the index doesn't slow things down too much
- [ ] Get full suite passing reliably

**Comment by adamcfraser** [comment]
Tests identified as intermittently failing associated with this:
 - [TestAccessOnTombstone](http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/491/console)

**Comment by tleyden** [comment]
@adamcfraser does this look like the expected output in a sporadic failure?

https://gist.github.com/tleyden/846f66b1d2706322161235956bf83ec1

One thing I'm confused about is that even after setting the slowquerytimeout warning to something very small (`base.SlowQueryWarningThreshold = time.Millisecond * 2`) I'm not seeing queries take long enough that I'd expect them to cause the test to fail:

```
2018-04-26T17:17:04.752-07:00 [INF] Query: N1QL Query("access") took 25.028681ms
2018-04-26T17:17:04.759-07:00 [INF] Query: N1QL Query("roleAccess") took 7.637038ms
```

or would you expect to see [these warnings](https://github.com/couchbase/sync_gateway/blob/131be9ad29bd5968fb14ac91d9dd5c18d87c0440/base/bucket_n1ql.go#L69-L74) during the sporadic failures?

**Comment by tleyden** [comment]
I kicked off some integration tests that ran `TestLowSequenceHandlingWithAccessGrant` in a loop 10 times (http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/551/parameters/), but there were no failures. 

Ditto for `TestLowSequenceHandling` and `TestLowSequenceHandlingWithAccessGrant`.

Btw I'm planning to change the integration test job to make it possible to run all three tests via `TestLowSequence`

**Comment by tleyden** [comment]
More details from integration run http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/572/consoleFull:

In the failing test, the index verification passes:

```

2018-05-03T12:12:39.585-07:00 [INF] Initializing indexes with numReplicas: 0...
2018-05-03T12:12:40.052-07:00 [INF] Verifying index availability for bucket test_data_bucket...
2018-05-03T12:12:40.052-07:00 [INF] Query: Executing N1QL query: &{options:map[statement:SELECT  [op.name, LEAST(`test_data_bucket`._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)][1] AS sequence FROM `test_data_bucket` UNNEST OBJECT_PAIRS(`test_data_bucket`._sync.channels) AS op WHERE [op.name, LEAST(`test_data_bucket`._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)]  BETWEEN  ['foo', 0] AND ['foo', 1] ORDER BY sequence LIMIT 1 scan_consistency:request_plus] adHoc:true}
2018-05-03T12:12:40.052-07:00 [INF] Query: Executing N1QL query: &{options:map[statement:SELECT `test_data_bucket`._sync.access.foo as val FROM `test_data_bucket` WHERE ANY op in OBJECT_PAIRS(`test_data_bucket`._sync.access) SATISFIES op.name = 'foo' end LIMIT 1 scan_consistency:request_plus] adHoc:true}
2018-05-03T12:12:40.052-07:00 [INF] Query: Executing N1QL query: &{options:map[statement:SELECT `test_data_bucket`._sync.role_access.foo as val FROM `test_data_bucket` WHERE ANY op in OBJECT_PAIRS(`test_data_bucket`._sync.role_access) SATISFIES op.name = 'foo' end LIMIT 1 scan_consistency:request_plus] adHoc:true}
2018-05-03T12:12:40.061-07:00 [INF] Query: Done executing N1QL query: &{options:map[scan_consistency:request_plus statement:SELECT  [op.name, LEAST(`test_data_bucket`._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)][1] AS sequence FROM `test_data_bucket` UNNEST OBJECT_PAIRS(`test_data_bucket`._sync.channels) AS op WHERE [op.name, LEAST(`test_data_bucket`._sync.sequence, op.val.seq),IFMISSING(op.val.rev,null), IFMISSING(op.val.del,null)]  BETWEEN  ['foo', 0] AND ['foo', 1] ORDER BY sequence LIMIT 1] adHoc:true}.  Error: <nil>
2018-05-03T12:12:40.064-07:00 [INF] Query: Done executing N1QL query: &{options:map[statement:SELECT `test_data_bucket`._sync.role_access.foo as val FROM `test_data_bucket` WHERE ANY op in OBJECT_PAIRS(`test_data_bucket`._sync.role_access) SATISFIES op.name = 'foo' end LIMIT 1 scan_consistency:request_plus] adHoc:true}.  Error: <nil>
2018-05-03T12:12:40.065-07:00 [INF] Query: Done executing N1QL query: &{options:map[scan_consistency:request_plus statement:SELECT `test_data_bucket`._sync.access.foo as val FROM `test_data_bucket` WHERE ANY op in OBJECT_PAIRS(`test_data_bucket`._sync.access) SATISFIES op.name = 'foo' end LIMIT 1] adHoc:true}.  Error: <nil>
2018-05-03T12:12:40.065-07:00 [INF] Indexes ready for bucket test_data_bucket.
```

However after what appears to be a *delayed reaction* to the bucket flush, the queries start returning `indexer rollback` errors:

```
2018-05-03T12:12:45.182-07:00 [WRN] Indexer error during query - retry 9/30 after 2.56s. -- base.(*CouchbaseBucketGoCB).Query() at bucket_n1ql.go:73
2018-05-03T12:12:47.758-07:00 [WRN] Indexer error during query - retry 10/30 after 5.12s. -- base.(*CouchbaseBucketGoCB).Query() at bucket_n1ql.go:73
```

Which causes the test to fail.  

(Note: as can be seen on the feature/issue_3422_gsi_timeout branch, I had to bump the "waitForSequence" timeout to 30s and enable extra logging.)

Here are the raw logs:

https://gist.github.com/tleyden/8d1d1507d04d99e8086d106d371a93ff

**Comment by tleyden** [comment]
As a workaround attempt, I'm experimenting w/ dropping and recreating indexes during the test setup.

**Comment by tleyden** [comment]
Dropping the indexes before the bucket flush seems to be working well.  However, it's slowing the tests down quite a bit due to the extra work -- it looks the VM where this is running on might be *severely underprovisioned*.

I just compared performance against an AWS m4.4xlarge instance, and the difference looks pretty staggering.

| Host       | Couchbase Server locality | Test           | Time  |
| ------------- | ------------- | ------------- | ----- |
| Jenkins VM      |  Different Machine | TestGetRemoved | 91.30s |
| AWS m4.4xlarge    | Same Machine |  TestGetRemoved | 7.08s |

Regarding the **Couchbase Server locality** column -- aside from more cores / RAM, the test on AWS is using the same machine to run the test suite and the Couchbase Server instance.   However, it seems like the increase in machine resources would be the source of the slowness rather than the connection between the two, but just mentioning it for completeness.

Partial logs for both runs: 

https://gist.github.com/tleyden/4f299e5c8496a364c63788a39b0890f7

**Comment by tleyden** [comment]
On AWS, the full suite integration suite completed in 1.6 hours when dropping indexes before flushing buckets.

The last jenkins run I attempted timed out after a single package took more than 3 hours.

**Comment by tleyden** [comment]
@adamcfraser I was thinking of adding an env variable `SG_TEST_DROP_INDEXES`:

- True: drops all GSI indexes before flushing the buckets.  This is slower, but less chance of hitting sporadic failures related to this issue.  Might be more appropriate for nightly builds.
- False: (default).  The current behavior, where it will not try dropping the indexes.  Faster, but risks hitting this issue.

**Comment by tleyden** [comment]
Also, there are a lot of tests which specifically test views (eg, `TestViewQuery`), and in those cases there should be a way to explicitly mark them as not needing to drop the GSI indexes, regardless of what the `SG_TEST_DROP_INDEXES` setting is.

I was thinking of adding a property to the `RestTester` called `NoDropIndexes`.  If set, it would skip the index dropping step.

**Comment by adamcfraser** [comment]
I agree about the environment variable.  

Adding the `NoDropIndexes` property feels like it adds complexity to the tests (having to decide which RestTester to use when writing a new test), and I'm not sure there are *that* many tests that would want to bypass dropping the indexes.  Anything that does auth has a dependency on query, and it feels like it would be easy to forget to switch back to enabling drop indexes if we tweaked a test in future to move from the admin to public port (say).

**Comment by tleyden** [comment]
I've added the env variable, and skipped the `NoDropIndexes` property for now.  PR up at https://github.com/couchbase/sync_gateway/pull/3544
