### ISSUE TITLE
Delta Sync epic

### ISSUE THREAD

**Issue by bbrks** [couchbase/sync_gateway#3720]
Tracking issue for the Delta Sync epic:

- [x] #3702 Technical Spec
- [x] https://github.com/couchbaselabs/go-jsondiffpatch/issues/1 Implement Fleece deltas in Go
- [x] https://github.com/couchbaselabs/go-jsondiffpatch/issues/2 Automated Go/Fleece compatibility tests
- [x] #3315 EE Builds
- [ ] #3715 Delta Sync config
- [ ] #3716 Replication Protocol negotiation
- [ ] #3717 CBL Push flow
- [ ] #3718 CBL Pull flow
- [ ] #3719 Expvar stats
- [ ] #TODO Perf enhancements (cache deltas in memory)
- [ ] #TODO Perf enhancements (cache deltas in memory)
- [ ] #TODO end-to-end testing of CBL Push flow
- [ ] #TODO end-to-end testing of CBL Pull flow
