### ISSUE TITLE
SG Mercury Epic

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#3761]
## Planning

- [ ] Finalize Product Requirements Doc
- [ ] Finalize Technical Spec

## P0 Dev tasks

- [ ] Mobile service integration with ns-server
    - [ ] Integration mobile service into ns-server build
    - [ ] Spawned by ns-server with expected args.  ([prototype code](https://github.com/tleyden/ns_server/blob/sg_cbs_integration3/src/ns_ports_setup.erl#L656-L709))
    - [ ] ns-server must be aware of mobile-service in several places in the codebase ([prototype code](https://github.com/tleyden/ns_server/commit/193b483381ba9a3c4159f6946969e3bc553e5738))
    - [ ] Enhance the ns-server UI to display mobile-service as a service (not prototyped)
    - [ ] Decide port allocation for GRPC and UI REST API
    - [ ] gocb support for mobile service node retrieval 
- [ ] Unit Test Plan
- [ ] Config Exchange 
    - [ ] Load full config during gateway startup
    - [ ] Mobile service pushes all config changes to gateway nodes
    - [ ] Gateway nodes react to config changes 
- [ ] Stats exchange/storage for existing stats
   - [ ] Push stats from gateway -> mobile service, store in ring buffer
   - [ ] Expose REST api from mobile service to ns-stats
   - [ ] Find or build CLI stats dump util
- [ ] Gateway presence
    - [ ] Detect when gateway nodes disappear and update state
    - [ ] Detect when mobile service node topology changes 
- [ ] Sharded convergence import 
- [ ] Sg-Replicate HA
- [ ] UI Rest API (note: could this be auto-generated from a GRPC api?)
    - [ ] Design swagger spec 
    - [ ] Build actual rest api endpoints 
- [ ] Implement security 
    - [ ] Send ns-server team spec on how to create Mobile RBAC roles
    - [ ] TLS mode for UI REST API
    - [ ] TLS mode for GRPC 
- [ ] Import legacy static file config
    - [ ] Static file config backwards compatibility tool for QE functional testing
- [ ] Support newly added stats
    - [ ] OS level cpu/memory
    - [ ] Newly added sg-replicate stats

## P0 Tooling 

- [ ] Backup / restore of config
- [ ] Cbcollect_info enhancements

## P1 Dev tasks

- [ ] Advanced runtime configuration changes
    - [ ] Handling server restarts on port changes

## Deprecated 

This should be tracked somewhere else.  

- [ ] Remove deprecated functionality related to configuration being removed
    - [ ] [adminUI](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#adminUI)
    - [ ] [configServer](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#configServer)
    - [ ] [feed_type](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#databases-foo_db-feed_type)
    - [ ] [pretty](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#pretty)
    - [ ] [profileInterface](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#profileInterface)
    - [ ] [channel_index](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#databases-foo_db-channel_index)
    - [ ] [enable_shared_bucket_access](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#databases-foo_db-enable_shared_bucket_access) -- not decided yet if will default to xattrs
    - [ ] [Import_docs](https://docs.couchbase.com/sync-gateway/2.1/config-properties.html#databases-foo_db-import_docs) -- not decided yet if will default to xattrs

**Comment by tleyden** [comment]
Moved to https://issues.couchbase.com/browse/CBG-73
