### ISSUE TITLE
AWS perfcluster kicked off from Jenkins

### ISSUE THREAD

**Issue by tleyden** [couchbase/sync_gateway#824]
Parameters
- Cluster (topology -- how many servers are involved)
- Gateload/Gating -- scenario + parameters to scenarios (pushes/pullers)
- Sync Gateway paremeter set (n readers, m writers)

**Comment by tleyden** [comment]
## Phase I

Currently in order to kick off a test on a running cluster:
1. Setup, some of which is manual, some of which is automated by ansible scripts
2. Manually flush couchbase bucket(s) to clear data from previous run
3. Call ansible-playbook to restart sync gateway (in fact, not sure if even needed)
4. Call ansible-playbook to kick off gateload jobs 
5. If different number of pushers / pullers needed: need to manually update gateload configs
6. If different version of couchbase server needed:
   1. Uninstall couchbase server
   2. Re-install couchbase server with correct version
   3. Manually setup cluster
7. Manually collect results:
   1. Fetch gateload expvars (before the processes die)
   2. Fetch sync gateway expvars 
   3. Fetch sync gateway heap and memory profile data 

In phase I, the equivalent of the above should be possible to do by kicking off a Jenkins job which takes the minimal parameters:
- Couchbase server version 
- Sync Gateway version (either released version or branch)
- Number of Sync Gateway writers
- Number of pushers / pullers for each gateload

## Phase I tasks
- [ ] Create Jenkins job + worker which has Ansible installed

jenkins setup now a different ticket - https://github.com/couchbase/sync_gateway/issues/1143
- [x] Ability to automatically setup a couchbase cluster via Ansible
- [ ] Gateload should take a new parameter `--expvar-output-file`.  Before it finishes, it will write its current expvar json snapshot to that file so that it can later be collected. 
- [ ] Gateload should have the ability to have the pushers and pullers passed on the command line, which would override the values in the config.
- [ ] Gateload: ditto for user offset value
- [ ] Gateload: ditto for sync gateway hostname

Gateload tasks here now - https://github.com/couchbase/sync_gateway/issues/1142

**Comment by tleyden** [comment]
Should be three decoupled Jenkins tasks:
- [x] Spinup cluster
- [x] Kick off tests
- [x] Teardown cluster

**Comment by tleyden** [comment]
Ansible scripts repo:  https://github.com/couchbaselabs/perfcluster-aws

**Comment by sethrosetter** [comment]
Also number of gateload nodes should be parameterized

**Comment by tleyden** [comment]
A few crucial additional parameters needed:
- [x] Sync Gateway branch to test
- [x] Sync Gateway config file or URL to use during the test (I think to start with, a single config used by all nodes makes sense, later we can look into mapping certain configs to certain SG nodes)
- [ ] The buckets that need to be created on the Couchbase Cluster, because certain testing requires multiple buckets -- for example one bucket for primary Sync Gateway data, and another for the Distributed Index data.

The last one about the buckets is probably the trickiest.  Ideally, everytime a job was kicked off something would kick and read the Sync Gateway config, see the list of buckets that are used, (there are a small number of places to look in the config json to find this out), and make sure those buckets are created before running the test.

Now here - Bucket config ticket - https://github.com/couchbase/sync_gateway/issues/1144

**Comment by sethrosetter** [comment]
Now filed here - splunk paramaterization - https://github.com/couchbase/sync_gateway/issues/1145

I will also investigate parameterizing Splunk 
- [ ] Endpoint
- [ ] On / Off

**Comment by sethrosetter** [comment]
Per conversation with @tleyden. I did not work with gateload for phase one. The idea was to get gatling running.

**Comment by sethrosetter** [comment]
Added gateload items to a separate ticket - https://github.com/couchbase/sync_gateway/issues/1142

**Comment by sethrosetter** [comment]
Actually jenkins setup now a different ticket - https://github.com/couchbase/sync_gateway/issues/1143

**Comment by sethrosetter** [comment]
Bucket config now low priority according to https://github.com/couchbaselabs/perfcluster-aws/issues/12

**Comment by sethrosetter** [comment]
Bucket config ticket - https://github.com/couchbase/sync_gateway/issues/1144

**Comment by sethrosetter** [comment]
splunk paramaterization - https://github.com/couchbase/sync_gateway/issues/1145

**Comment by sethrosetter** [comment]
Closing. This has been split into individual tickets
